name: Build and Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests - Models
        run: dotnet test ./tests/TicTacToe.Tournament.Models.Tests --no-restore --no-build --configuration Release

      - name: Run Unit Tests - Server
        run: dotnet test ./tests/TicTacToe.Tournament.Server.Tests --no-restore --no-build --configuration Release

      - name: Run Unit Tests - Auth
        run: dotnet test ./tests/TicTacToe.Tournament.Auth.Tests --no-restore --no-build --configuration Release

      - name: Run Unit Tests - Player
        run: dotnet test ./tests/TicTacToe.Tournament.Player.Tests --no-restore --no-build --configuration Release
