name: Build and Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  checks: write
  pull-requests: write
  contents: read
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore all dependencies
        run: dotnet restore src/TicTacToe.Tournament.sln

      - name: Build entire solution
        run: dotnet build src/TicTacToe.Tournament.sln --no-restore --configuration Release

      - name: Run Unit Tests - All Unit Tests
        run: |
          mkdir -p TestResults
          for proj in $(find src -name "*.Tests.csproj"); do
            dotnet test "$proj" --no-build --configuration Release \
              --logger "trx;LogFileName=$(basename $proj .csproj).trx" \
              --results-directory TestResults
          done

      - name: Upload TRX Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/*.trx

      - name: Publish Test Report as PR Comment
        uses: dorny/test-reporter@v1
        if: github.event_name == 'pull_request'
        with:
          name: Tests Report
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Publish Test Results to GitHub Actions UI
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: TestResults/*.trx
