name: Build and Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore all dependencies
        run: dotnet restore src/TicTacToe.Tournament.sln

      - name: Build entire solution
        run: dotnet build src/TicTacToe.Tournament.sln --no-restore --configuration Release

      - name: Run Unit Tests - All Unit Tests
        run: |
          dotnet test src/TicTacToe.Tournament.Auth.Tests/TicTacToe.Tournament.Auth.Tests.csproj --no-build --configuration Release
          dotnet test src/TicTacToe.Tournament.Models.Tests/TicTacToe.Tournament.Models.Tests.csproj --no-build --configuration Release
          dotnet test src/TicTacToe.Tournament.Server.Tests/TicTacToe.Tournament.Server.Tests.csproj --no-build --configuration Release
          dotnet test src/TicTacToe.Tournament.Player.Tests/TicTacToe.Tournament.Player.Tests.csproj --no-build --configuration Release
          dotnet test src/TicTacToe.Tournament.SmartPlayer.Tests/TicTacToe.Tournament.SmartPlayer.Tests.csproj --no-build --configuration Release
